spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.190.159.10:3306/user_test?characterEncoding=utf-8&useSSL=false
        username: root
        password: Yasong0120.
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 200 #最大连接数
        initialSize: 1 #初始化连接
        maxWait: 60000 #连接超时时间
        minIdle: 1     #最小连接数
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000 #最大空闲时间
     #   validationQuery: select 'x'  不用该配置性能较高
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        host: 118.190.159.10
        database: 0
        port: 6379
        password: Yasong0120.
        jedis:
            pool:
                max-active: 200
                max-wait: -1
                max-idle: 10
                min-idle: 0
        timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yasong.yin.playinggo.entity

server:
  port: 8088
ys:
  name: yinyasong




